Q7. Write and explain the output of the following program? 

public class JavaHungry {
    public static void main(String args[])
    {
        try 
        {   
            int arr[]= {1, 2, 3, 4, 5}; 
            for (int i = 0; i <= 5; i++) 
            { 
                System.out.print ("Array elements are : " + arr[i] + "\n"); 
            } 
        } 
        catch (Exception e) 
        { 
            System.out.println ("Exception : " + e); 
        } 
        catch (ArrayIndexOutOfBoundsException ex) 
        { 
            System.out.println ("ArrayIndexOutOfBoundsException : "+ ex); 
        }  
    }
}


SOLUTION
The above program wonâ€™t run because the first catch statement is catching an exception of a parent class before than a sub - class, so best practice to write multiple catch statements in exception handling is to catch specific exceptions at first and than at the last we should catch exception of a parent class i.e the Exception class.
